### ISSUE TITLE
image = "0.21.0" breaks examples

### ISSUE THREAD

**Issue by gamecubate** [tversteeg/blit#4]
Using image = "0.20.0" restores functionality of examples.

**Comment by tversteeg** [comment]
Thank you! I've reverted them both to 0.20. Are you actively using this library?

**Comment by gamecubate** [comment]
> I've reverted them both to 0.20.
Thanks for that. I will validate your main documentation example shortly and will let you know how it went.

> Are you actively using this library?
I'm in the process of evaluating it for now. I'm not certain it will work for me, though, as what I am really looking for is to, given an assortment of (programmatically generated) buffers, blit from one (buffer) to another, and from that other to a third one, and, finally, from that third buffer to one tied to the application view. Think multi-layer drawing application.

**Comment by tversteeg** [comment]
> I'm in the process of evaluating it for now. I'm not certain it will work for me, though, as what I am really looking for is to, given an assortment of (programmatically generated) buffers, blit from one (buffer) to another, and from that other to a third one, and, finally, from that third buffer to one tied to the application view. Think multi-layer drawing application.

This is exactly the goal for which I've written this library. I'm using it as the only drawing method in this game that I made (but didn't finish): https://github.com/tversteeg/castle-game
